spring:
  application:
    name: redis-cache
---
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/sample
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      cache-null-values: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect